spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: chatbot
  autoconfigure:
    exclude:
      - org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration

  # Configure OpenRouter API key (replace with your actual API key)
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: ${ANTHROPIC_API_KEY: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}

      # Specify the model you want to use (e.g., a free one, check the OpenRouter site for options)
      chat:
        options:
          model: openai/gpt-oss-20b

    #needed to disable spring AI's autoconfigure to anthropic.
    model:
      chat: openai
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false

server:
  port: 8080

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY}
user:
  name: ${USER_NAME}
  password: ${USER_PASSWORD}




