spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: chatbot
  autoconfigure:
    exclude:
      - org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration

  # Configure OpenRouter API key (replace with your actual API key)
  ai:
    openai:
      api-key: ${ANTHROPIC_API_KEY:missing-key}
      base-url: https://openrouter.ai/api

      # Specify the model you want to use (e.g., a free one, check the OpenRouter site for options)
      chat:
        options:
          model: openai/gpt-oss-20b

    #needed to disable spring AI's autoconfigure to anthropic.
    model:
      chat: openai
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false

server:
  port: 8080



