# copilot/chatbot/addons/users-table.yml
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-${Name}-UsersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: StatId 
          AttributeType: S
      KeySchema:
        - AttributeName: StatId
          KeyType: HASH
